### PR TITLE
Added UpSkill-App Solution to repo

### PR DESCRIPTION
**Pull request by NellyIfandieva**

### CODE REVIEW

**Review by Hristoki — COMMENTED** [review]
So far so good but this is only an empty solution. According to the issue you also have to add Blazor Web Assembly Project with PWA enabled.

**Review by Hristoki — APPROVED** [review]
The default code needs to be cleaned up later but for the time being I think the examples will be useful for those of us who haven't used Blazor before. :)

**Comment by NellyIfandieva** [comment]
> The default code needs to be cleaned up later but for the time being I think the examples will be useful for those of us who haven't used Blazor before. :)

I think I can also watch for the branch name next time...

**Review by Hristoki — APPROVED** [review]

**Review by YavorTsanev — APPROVED** [review]
this is exactly what we need

**Pull request merged**
