### PR TITLE
Implemented basic working registration

### PR DESCRIPTION
**Pull request by Hristoki**
#57

- Added AccountApiController
- Added RegistrationDto
- Added Response Dto
- Removed some required attributes from Model to facilitate registration testing
- The registration method will be refactored and improved after account service is introduced

### CODE REVIEW

**Review by YavorTsanev — DISMISSED** [review]
Works fine, I successfully saved data in Db via Register ApiController

**Review by martin-ali — APPROVED** [review]

**Review by martin-ali — COMMENTED** [review]
AccountsController has a formatting issue for the using System.Collections.Generic

**Review by martin-ali — DISMISSED** [review]

**Comment by mustafaiam** [comment]
Looks fine to me! 😄

**Review by mustafaiam — APPROVED** [review]
Looks fine to me! 😄 Except the formatting issue in the AccountsController in line 8 but that can be fixed in less than a minute.

**Pull request merged**
