### PR TITLE
Implemented repository pattern

### LINKED ISSUE #36: Implement repository pattern
Implement repository pattern

### PR DESCRIPTION
**Pull request by martin-ali**
Closes #36

### CODE REVIEW

**Review by YavorTsanev — APPROVED** [review]
Look like a nice copy/paste, i seem you know what you doing

**Comment by martin-ali** [comment]
Dismiss-а е автоматичен

**Review by YavorTsanev — APPROVED** [review]

**Comment by NellyIfandieva** [comment]
Looks what we need for the moment.

**Comment by NellyIfandieva** [comment]
Looks just what we need at least for now.

**Review by YavorTsanev — APPROVED** [review]

**Review by NellyIfandieva — APPROVED** [review]
Great!

**Pull request merged**
